CREATE TABLE tblinscricao(

	  CODIGO_INSCRICAO int AUTO_INCREMENT,
	  PAGAMENTO  varchar(3) default 'não',
	  CPF_PARTICIPANTE  varchar(15),
	  NOME_PARTICIPANTE  varchar(200),
	  DATA_INSCRICAO  TIMESTAMP,
	  PRIMARY KEY (CODIGO_INSCRICAO)

 );
  
  CREATE TABLE tblevento(

   CODIGO_EVENTO int AUTO_INCREMENT,
   NOME_EVENTO 	 varchar(50) NOT NULL,
   CARGA_HORARIA time NULL,
   VALOR_EVENTO 	 numeric(10,2),
   DATA_EVENTO_INICIO date NOT NULL,
   DATA_EVENTO_FIM date NOT NULL,
   DESCRICAO_EVENTO varchar(200),
   PRIMARY KEY(CODIGO_EVENTO)

 );